library(Seurat)
library(future)
library(tximport)
library(SeuratWrappers)
cells_7dpi<-ReadAlevin("~/LABLIFE/DANIO_RERIO/ALEVIN/7DPI/alevin/quants_mat.gz")
cells_7dpi@project.name<-"7DPI"
cells_7dpi<-SetIdent(cells_7dpi, value = "7DPI")
cells_7dpi@meta.data[["orig.ident"]]<-"7DPI"
cells_13dpi<-ReadAlevin("~/LABLIFE/DANIO_RERIO/ALEVIN/13DPI/alevin/quants_mat.gz")
cells_13dpi@project.name<-"13DPI"
cells_13dpi<-SetIdent(cells_13dpi, value = "13DPI")
cells_13dpi@meta.data[["orig.ident"]]<-"13DPI"
cells_21dpi<-ReadAlevin("~/LABLIFE/DANIO_RERIO/ALEVIN/21DPI/alevin/quants_mat.gz")
cells_21dpi@project.name<-"21DPI"
cells_21dpi<-SetIdent(cells_21dpi, value = "21DPI")
cells_21dpi@meta.data[["orig.ident"]]<-"21DPI"
all.cells<-merge(x=cells_7dpi, y=c(cells_13dpi, cells_21dpi), add.cell.ids=c("7DPI", "13DPI", "21DPI"), project="combined", merge.data=T)
all.cells<-JoinLayers(all.cells)
all.cells<-PercentageFeatureSet(all.cells, pattern = "^mt-", col.name = "percentage.mt")
cells_7dpi<-PercentageFeatureSet(cells_7dpi, pattern = "^mt-", col.name = "percentage.mt")
cells_13dpi<-PercentageFeatureSet(cells_13dpi, pattern = "^mt-", col.name = "percentage.mt")
cells_21dpi<-PercentageFeatureSet(cells_21dpi, pattern = "^mt-", col.name = "percentage.mt")
all.cells<-subset(all.cells, subset =  nFeature_RNA > 100 & nFeature_RNA < 2500 & percentage.mt < 25 )
all.cells<-NormalizeData(all.cells, normalization.method = "CLR", margin = 1, block.size = 1)
cells_7dpi<-subset(cells_7dpi, subset = nFeature_RNA > 200 & percentage.mt < 25)
cells_7dpi<-NormalizeData(cells_7dpi, normalization.method = "CLR", margin = 2, block.size = 1)
cells_13dpi<-subset(cells_13dpi, subset = nFeature_RNA > 200 & percentage.mt < 25 )
cells_13dpi<-NormalizeData(cells_13dpi, normalization.method = "CLR", margin = 2, block.size = 1)
cells_21dpi<-subset(cells_21dpi, subset = nFeature_RNA > 200 & percentage.mt < 25 )
cells_21dpi<-NormalizeData(cells_21dpi, normalization.method = "CLR", margin = 2, block.size = 1)
macrophages_7dpi<-subset(cells_7dpi, subset = MFAP4 > 0 | mfap4.4 > 0 | mfap4.2 > 0 | mfap4.1 > 0 | mfap4.10 > 0)
macrophages_13dpi<-subset(cells_13dpi, subset = MFAP4 > 0 | mfap4.4 > 0 | mfap4.2 > 0 | mfap4.1 > 0 | mfap4.10 > 0)
macrophages_21dpi<-subset(cells_21dpi, subset = MFAP4 > 0 | mfap4.4 > 0 | mfap4.2 > 0 | mfap4.1 > 0 | mfap4.10 > 0)
all.macrophages<-subset(all.cells, subset = MFAP4 > 0 | mfap4.4 > 0 | mfap4.2 > 0 | mfap4.1 > 0 | mfap4.10 > 0)
all.macrophages<-merge(macrophages_7dpi, c(macrophages_13dpi, macrophages_21dpi), add.cell.ids=c("7DPI", "13DPI", "21DPI"), project="macrophages.combined", merge.data=T)
all.macrophages<-JoinLayers(all.macrophages)
all.macrophages<-PercentageFeatureSet(all.macrophages, pattern = "^mt-", col.name = "percentage.mt")
VlnPlot(all.macrophages, features = c("nFeature_RNA", "nCount_RNA", "percentage.mt"))
all.macrophages<-subset(all.macrophages, subset = nFeature_RNA > 100 & nFeature_RNA < 2500 & percentage.mt < 25)
VlnPlot(all.macrophages, features = c("nFeature_RNA", "nCount_RNA", "percentage.mt"))
VlnPlot(cells_7dpi, features = c("nFeature_RNA", "nCount_RNA", "percentage.mt"))
VlnPlot(cells_13dpi, features = c("nFeature_RNA", "nCount_RNA", "percentage.mt"))
VlnPlot(cells_21dpi, features = c("nFeature_RNA", "nCount_RNA", "percentage.mt"))
all.macrophages<-FindVariableFeatures(all.macrophages, nfeatures = 5000)
all.cells<-FindVariableFeatures(all.cells, nfeatures = 5000)
cells_7dpi<-FindVariableFeatures(cells_7dpi, nfeatures = 5000)
cells_13dpi<-FindVariableFeatures(cells_13dpi, nfeatures = 5000)
cells_21dpi<-FindVariableFeatures(cells_21dpi, nfeatures = 5000)
all.macrophages<-ScaleData(all.macrophages, vars.to.regress = c("nCount_RNA"), block.size = 1)
all.cells<-ScaleData(all.cells, vars.to.regress = c("nCount_RNA"), block.size = 1)
cells_7dpi<-ScaleData(cells_7dpi, vars.to.regress = c("percentage.mt", "nFeature_RNA"), block.size = 1)
cells_13dpi<-ScaleData(cells_13dpi, vars.to.regress = c("percentage.mt", "nFeature_RNA"), block.size = 1)
cells_21dpi<-ScaleData(cells_21dpi, vars.to.regress = c("percentage.mt", "nFeature_RNA"), block.size = 1)
all.macrophages<-RunPCA(all.macrophages, rev.pca = T, npcs = 20)
ElbowPlot(all.macrophages, ndims = 20)
all.cells<-RunPCA(all.cells, npcs = 200, rev.pca=T)
ElbowPlot(all.cells, ndims = 30)
cells_7dpi<-RunPCA(cells_7dpi, npcs = 200)
ElbowPlot(cells_7dpi, ndims = 30)
cells_13dpi<-RunPCA(cells_13dpi, npcs = 200)
ElbowPlot(cells_13dpi, ndims = 30)
cells_21dpi<-RunPCA(cells_21dpi, npcs = 200)
ElbowPlot(cells_21dpi, ndims = 30)
all.macrophages<-FindNeighbors(all.macrophages, dims = 1:15, k.param = 15)
all.cells<-FindNeighbors(all.cells, k.param = 99)
cells_7dpi<-FindNeighbors(cells_7dpi)
cells_13dpi<-FindNeighbors(cells_13dpi)
cells_21dpi<-FindNeighbors(cells_21dpi)
all.macrophages<-FindClusters(all.macrophages)
all.macrophages<-JoinLayers(all.macrophages)
all.markers.macrophages<-FindAllMarkers(all.macrophages, only.pos = T)
all.cells<-FindClusters(all.cells)
all.markers<-FindAllMarkers(all.cells, only.pos = T)
cells_7dpi<-FindClusters(cells_7dpi)
cells_13dpi<-FindClusters(cells_13dpi)
cells_21dpi<-FindClusters(cells_21dpi)
all.macrophages<-RunUMAP(all.macrophages, dims = 1:15, n.neighbors = 15)
DimPlot(all.macrophages, reduction = "umap", label = T, label.box = T, split.by = "orig.ident")
cells_7dpi<-RunUMAP(cells_7dpi, dims = 1:10)
DimPlot(cells_7dpi, reduction = "umap")
cells_13dpi<-RunUMAP(cells_13dpi, dims = 1:10)
DimPlot(cells_13dpi, reduction = "umap")
cells_21dpi<-RunUMAP(cells_21dpi, dims = 1:10)
DimPlot(cells_21dpi, reduction = "umap")
all.cells<-RunUMAP(all.cells, n.neighbors = 99, dims = 1:15)
DimPlot(all.cells, reduction = "umap", split.by="orig.ident", label = T)
all.macrophages<-RunTSNE(all.macrophages)
DimPlot(all.macrophages, reduction = "tsne", split.by = "orig.ident")
DoHeatmap(all.cells, group.by = "orig.ident", features = VariableFeatures(all.cells, nfeatures = 50))
all.cells<-RunTSNE(all.cells, check_duplicates=F)
cells_7dpi<-RunTSNE(cells_7dpi, check_duplicates=F)
DimPlot(cells_7dpi, reduction = "tsne")
cells_13dpi<-RunTSNE(cells_13dpi, check_duplicates=F)
DimPlot(cells_13dpi, reduction = "tsne")
cells_21dpi<-RunTSNE(cells_21dpi, check_duplicates=F)
DimPlot(cells_21dpi, reduction = "tsne")
DimPlot(all.cells, reduction = "tsne", split.by = "orig.ident")
all.macrophages<-JoinLayers(all.macrophages)
allMarkers.macrophages<-FindAllMarkers(all.macrophages, only.pos = T)
markers_7dpi<-FindAllMarkers(cells_7dpi)
markers_13dpi<-FindAllMarkers(cells_13dpi)
markers_21dpi<-FindAllMarkers(cells_21dpi)
DoHeatmap(all.macrophages, group.by = "orig.ident", features = c("tnfa", "il1b", "irg1", "ccr2", "myd88", "asc", "caspb", "cxcl18b", "pge2", "alox12", "gata4", "blt1", "gpr37", "gpr18", "gpr32"))
markers_7DPI<-FindAllMarkers(all.macrophages, subset.ident="7DPI")
markers_clsuter1<-FindMarkers(all.macrophages, subset.ident="7DPI", ident.1 = 1)
#tabela cruzada para saber a porcentagem de celulas em cada cluster em cada dia:
prop.table(table(all.macrophages@meta.data$seurat_clusters, all.macrophages@meta.data$orig.ident), margin = 2)*100
